[package]
name = "ch04_02"
version = "0.1.0"
edition = "2024"

[dependencies]
mio ={ version = "0.8.8", features = ["net", "os-poll"]}
async-task = "4.4.0"
futures-lite = "1.12.0"
once_cell = "1.17.1"
flume = "0.10.14"
smol = "1.3.0"
anyhow = "1.0.71"
tokio = {workspace = true}